// charsDuck.js
export let GET_CHARACTERS = "GET_CHARACTERS";
export let GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export let GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR";
export let REMOVE_CHARACTER = "REMOVE_CHARACTER";
